version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  # Production service
  app-prod:
    build:
      context: .
      target: production
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
